### ISSUE TITLE
GPL vs. LGPL?

### ISSUE THREAD

**Issue by jaxley** [moxie0/AndroidPinning#14]
Noticed that this is a library but the published license is GPL vs. LGPL.  But that makes it unusable in commercial software or even many/most free mobile apps because GPL mandates the entire application be GPL in order to use GPL libraries.  https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL

Any possibility to change the license to LGPL to ensure contributions to the code remain public and free, but that the implementation can be used broadly?

**Comment by commonsguy** [comment]
The `README` for this project states:

> Please contact me if this license doesn't work for you

If contacting you via the issue tracker is not what you want, could you perhaps suggest an alternative way to contact you regarding licensing concerns?

Thanks!
