### ISSUE TITLE
AndroidPinning License

### ISSUE THREAD

**Issue by abstractj** [moxie0/AndroidPinning#7]
Hi my friend,

I'm currently working on Android projects and I think AndroidPinning is a good fit for my situation.

However the current license (GPLv3) prevents me to use AndroidPinning on anything, but only on fully opensource + GPL'd Android apps. Would it be possible to change AndroidPinning's license to a lesser restrictive one like BSD, MIT, ALv2, EPL…?

**Comment by moxie0** [comment]
If you'd like to get a dual license, feel free to contact me directly.  My contact info is on my website: http://www.thoughtcrime.org

Thanks
